window.AUDITFLOW_SAMPLE_DATA = [
  {
    id: 1,
    dispatchDate: "2026-02-05",
    reference: "AC/AUDIT/04/2026",
    officer: "Mr. Ashvir Raj",
    subject: "Nasinu Town Council Request for Additional $2.1m operational for SWM (FY 25/26)",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-02-05",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 2,
    dispatchDate: "2026-02-18",
    reference: "AC/AUDIT/04/2026",
    officer: "Mr. Ashvir Raj",
    subject: "Nasinu Town Council — file, minute and draft letter on the condition approval",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-02-18",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 3,
    dispatchDate: "2026-04-21",
    reference: "21-Apr-2026",
    officer: "Mr. Ashvir Raj",
    subject: "Response from Nasinu Town Council for additional operational grant for solid waste management ($1.5m)",
    purpose: "",
    recommendations: "",
    submittedTo: "Manager Finance",
    priority: "",
    dateSubmitted: "2026-04-21",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 4,
    dispatchDate: "2026-04-24",
    reference: "ANC-LTC COL",
    officer: "Mr. Ashvir Raj",
    subject: "Lami Town Council Compliance Report (FY 23/24 and FY 24/25)",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-04-24",
    currentLocation: "HM",
    status: "Pending with Minister",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 5,
    dispatchDate: "2026-04-24",
    reference: "AC/NTC 01/26",
    officer: "Mr. Ashvir Raj",
    subject: "Nausori Town Council Finance & HR Compliance Review (FY 23/24 to FY 24/25)",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-04-24",
    currentLocation: "",
    status: "Pending with Minister",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 6,
    dispatchDate: "2026-05-12",
    reference: "",
    officer: "Mr. Ashvir Raj",
    subject: "Submission of thirteen municipal council compliance check reports",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-05-12",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 7,
    dispatchDate: "2026-05-18",
    reference: "ANC/LTC 02/2026",
    officer: "Mr. Ashvir Raj",
    subject: "Establishment of a Committee of Inquiry under section 131 of the Local Government Act 1972",
    purpose: "",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-05-18",
    currentLocation: "",
    status: "Approved",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "Approved",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "Yes",
    followUpDate: "2026-06-15",
    followUpRemarks: "Followed up 15/06 with Viema; the minute had been delivered to the Minister.",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 8,
    dispatchDate: "2026-05-27",
    reference: "AC - NTC 02/26",
    officer: "Mr. Ashvir Raj",
    subject: "Vetting of NFA Quarter 3 grant acquittals — operational and emergency ambulance services grants",
    purpose: "Review",
    recommendations: "",
    submittedTo: "Manager Finance - Satveer",
    priority: "",
    dateSubmitted: "2026-05-27",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 9,
    dispatchDate: "2026-06-09",
    reference: "",
    officer: "Mr. Ashvir Raj",
    subject: "Six-month probation performance assessment — Ashvir Raj",
    purpose: "Other",
    recommendations: "",
    submittedTo: "HR - Samisoni",
    priority: "",
    dateSubmitted: "2026-06-09",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 10,
    dispatchDate: "2026-06-09",
    reference: "",
    officer: "Ms. Saidi Nazrana",
    subject: "Handover Report — PACO (Saidi Nazrana)",
    purpose: "Information",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-06-09",
    currentLocation: "",
    status: "",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 11,
    dispatchDate: "2026-06-09",
    reference: "AC - NTC 04/26",
    officer: "Mr. Ashvir Raj",
    subject: "Signing of documents to operationalise the Committee of Inquiry concerning Labasa Town Council",
    purpose: "Approval",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-06-09",
    currentLocation: "",
    status: "Approved",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "Approved",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "Yes",
    followUpDate: "2026-06-15",
    followUpRemarks: "Followed up 15/06 with Viema; the minute had been delivered to the Minister.",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 12,
    dispatchDate: "2026-06-11",
    reference: "AC - NTC 10/26",
    officer: "Mr. Ashvir Raj",
    subject: "Brief on staff grievance against Manager HR — Nausori Town Council",
    purpose: "Information",
    recommendations: "",
    submittedTo: "PS Office - Viema",
    priority: "",
    dateSubmitted: "2026-06-11",
    currentLocation: "",
    status: "Approved",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "Approved",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "Yes",
    followUpDate: "2026-06-15",
    followUpRemarks: "Followed up 15/06 with Viema; the minute had been delivered to the Minister.",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 13,
    dispatchDate: "2026-06-19",
    reference: "AC-MLG-22/2026",
    officer: "Mr. Ashvir Raj",
    subject: "Request for approval to purchase two monitor screens for the Audit & Compliance Unit",
    purpose: "Approval",
    recommendations: "",
    submittedTo: "MF - Navin Chandra",
    priority: "",
    dateSubmitted: "2026-06-19",
    currentLocation: "Manager Finance",
    status: "Submitted",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  },
  {
    id: 14,
    dispatchDate: "2026-06-23",
    reference: "AC-MLG-23/2026",
    officer: "Mr. Ashvir Raj",
    subject: "Preliminary findings from the $198,000 Miss Fiji and Miss Pacific Islands Pageant grant acquittal review",
    purpose: "Information",
    recommendations: "Management note the preliminary findings, request outstanding documents and explanations, set a response deadline, and reassess the acquittal after the additional information is received.",
    submittedTo: "MF - Navin Chandra",
    priority: "",
    dateSubmitted: "2026-06-23",
    currentLocation: "Manager Finance",
    status: "Submitted",
    expectedReturnDate: "",
    latestUpdate: "",
    decision: "",
    nextAction: "",
    implementationRequired: "",
    implementation: "",
    implementationStatus: "",
    followUpRequired: "",
    followUpDate: "",
    followUpRemarks: "",
    closureOutcome: "",
    dateClosed: ""
  }
];
